name: Build Kivy/KivyMD APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
              git zip unzip openjdk-11-jdk \
              python3-pip autoconf libtool pkg-config \
              zlib1g-dev cmake libffi-dev libssl-dev \
              libxml2-dev libxslt1-dev python3-dev \
              libsqlite3-dev libjpeg-dev libz-dev \
              libncurses6 build-essential

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools virtualenv
          pip install kivy==2.2.1 kivymd==1.1.1
          pip install cython==0.29.33
          pip install buildozer

      - name: Validate buildozer.spec
        run: |
          if grep -q '^fullscreen' buildozer.spec && grep -A5 '^fullscreen' buildozer.spec | grep -q '^fullscreen'; then
            echo "Error: Duplicate 'fullscreen' option found in buildozer.spec"
            exit 1
          fi

      - name: Run Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: helloworld-app
          path: bin/*.apk
