name: Build Kivy/KivyMD APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04  # Explicitly specify Ubuntu version
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          # First update with retries
          for i in {1..3}; do
            sudo apt-get update -y && break || sleep 5
          done
          
          # Install essential packages
          sudo apt-get install -y --no-install-recommends \
              git \
              zip \
              unzip \
              openjdk-11-jdk \
              python3-pip \
              autoconf \
              libtool \
              pkg-config \
              zlib1g-dev \
              cmake \
              libffi-dev \
              libssl-dev \
              libxml2-dev \
              libxslt1-dev \
              python3-dev \
              libsqlite3-dev \
              libjpeg-dev \
              libz-dev \
              libncurses6  # Modern alternative to libtinfo5

          # Install build essentials
          sudo apt-get install -y build-essential

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools virtualenv
          pip install kivy==2.2.1 kivymd==1.1.1
          pip install cython==0.29.33
          pip install buildozer

      - name: Run Buildozer
        run: |
          buildozer init
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: helloworld-app
          path: bin/*.apk
