name: Build Kivy/KivyMD APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git \
              zip \
              unzip \
              openjdk-11-jdk \
              python3-pip \
              autoconf \
              libtool \
              pkg-config \
              zlib1g-dev \
              libncurses5-dev \
              libncursesw5-dev \
              libtinfo5 \
              cmake \
              libffi-dev \
              libssl-dev

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip wheel setuptools virtualenv
          pip install kivy==2.2.1 kivymd==1.1.1
          pip install cython==0.29.33
          pip install buildozer

      - name: Run Buildozer
        run: |
          buildozer init
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: helloworld-app
          path: bin/*.apk
