name: Build Kivy/KivyMD APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 45  # Increased timeout for first build
    
    steps:
      - uses: actions/checkout@v4

      - name: Clean environment
        run: |
          rm -rf .buildozer bin/*
          sudo rm -rf /usr/local/lib/android/sdk/ndk/*

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
              git zip unzip openjdk-11-jdk \
              python3-pip autoconf libtool pkg-config \
              zlib1g-dev cmake libffi-dev libssl-dev \
              libxml2-dev libxslt1-dev python3-dev \
              libsqlite3-dev libjpeg-dev libz-dev \
              libncurses6 build-essential

      - name: Install Android NDK 25b
        run: |
          mkdir -p ~/.android
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip -d ~/.android/
          rm android-ndk-r25b-linux.zip
          echo "ANDROID_NDK_HOME=$HOME/.android/android-ndk-r25b" >> $GITHUB_ENV
          echo "NDK_HOME=$HOME/.android/android-ndk-r25b" >> $GITHUB_ENV
          echo "PATH=$HOME/.android/android-ndk-r25b:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK and tools
        run: |
          mkdir -p ~/.android
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip -d ~/.android/cmdline-tools
          mv ~/.android/cmdline-tools/cmdline-tools ~/.android/cmdline-tools/latest
          rm commandlinetools-linux-*.zip
          
          yes | ~/.android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.android/sdk "platform-tools" "platforms;android-33" "build-tools;33.0.0"
          echo "ANDROID_SDK_ROOT=$HOME/.android/sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/.android/sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools virtualenv
          pip install kivy==2.2.1 kivymd==1.1.1
          pip install cython==0.29.33
          pip install buildozer

      - name: Configure Buildozer
        run: |
          cat > buildozer.spec <<EOL
[app]
title = Hello World
package.name = helloworld
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,ttf
version = 0.1
requirements = python3==3.8.9,kivy==2.2.1,kivymd==1.1.1,openssl
orientation = portrait
fullscreen = 0
android.permissions = INTERNET
android.arch = arm64-v8a
android.api = 31
android.minapi = 21
android.ndk = $HOME/.android/android-ndk-r25b
android.sdk = $HOME/.android/sdk
android.accept_sdk_license = True

[buildozer]
log_level = 2
warn_on_root = 1
EOL

      - name: Run Buildozer with debug
        run: |
          buildozer -v android clean
          buildozer -v android debug 2>&1 | tee build.log
          grep -i error build.log && exit 1 || exit 0

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: helloworld-app
          path: bin/*.apk

      - name: Upload build log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
