name: Build Kivy APK for Poco C31
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk zlib1g-dev python3-pip
          pip install buildozer

      - name: Build signed APK
        run: |
          echo "android.arch = armeabi-v7a" >> buildozer.spec
          echo "android.minapi = 29" >> buildozer.spec
          buildozer android release

      - name: Sign APK (critical for Poco)
        run: |
          keytool -genkey -v -keystore my.keystore -alias myalias -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Unknown"
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my.keystore -storepass android ./bin/*.apk myalias

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Poco-App
          path: ./bin/*-release-unsigned.apk
